# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2011
  project: HybridAuth (Français)
  version: 3.1
  release: 3.1.2
  latex_documents:
  - - Index
    - px_hybrid_auth.tex
    - HybridAuth
    - André Wuttig
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
