# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2015
  project: HybridAuth (Deutsch)
  version: 3.0
  release: 3.0.0
  latex_documents:
  - - Index
    - px_hybrid_auth.tex
    - HybridAuth
    - Andr√© Wuttig
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
